<?php
declare(strict_types=1);

require __DIR__ . '/../../vendor/autoload.php';

use SebastianBergmann\CodeCoverage\CodeCoverage;
use SebastianBergmann\CodeCoverage\Driver\Xdebug3Driver;
use SebastianBergmann\CodeCoverage\Filter;
use SebastianBergmann\CodeCoverage\RawCodeCoverageData;
use SebastianBergmann\CodeCoverage\Report\Html\Facade as HtmlReport;

// The source dir to keep in the report. Defaults to the CI runner path so it works
// on GitHub Actions, but can be overridden (e.g. COVERAGE_SRC_DIR=/var/www/html/src)
// to run locally.
$srcDir = getenv('COVERAGE_SRC_DIR') ?: '/home/runner/work/tsumego-hero/tsumego-hero/src';
$includePrefix = rtrim($srcDir, '/') . '/';

function isExcluded($fileName): bool
{
	global $includePrefix;
	return !str_starts_with($fileName, $includePrefix);
}

$filter = new Filter();
$filter->includeDirectory($srcDir);
$driver = new Xdebug3Driver($filter);
$mergedRaw = [];
$mergedCount = 0;
$skipped = 0;

foreach (glob('/tmp/coverage/webservercoverage*.cov') as $file) {
	$data = @file_get_contents($file);
	if ($data === false) continue;

	$decoded = @unserialize($data);
	if ($decoded instanceof CodeCoverage) {
		// Directly merge newer-format files
		$raw = $decoded->getData(true);
		$array = $raw->asArray();
	} elseif (is_array($decoded)) {
		// Raw Xdebug array
		$array = $decoded;
	} else {
		$skipped++;
		continue;
	}

	// Merge arrays efficiently
	foreach ($array as $fileName => $lines) {
		if (isExcluded($fileName)) {
			continue;
		}
		if (!isset($mergedRaw[$fileName])) {
			$mergedRaw[$fileName] = $lines;
		} else {
			foreach ($lines as $line => $hit) {
				if (($mergedRaw[$fileName][$line] ?? 0) !== 1 && $hit === 1) {
					$mergedRaw[$fileName][$line] = 1;
				}
			}
		}
	}

	$mergedCount++;
}

echo "[merge] Found {$mergedCount} valid coverage files, {$skipped} skipped\n";

$coverage = new CodeCoverage($driver, $filter);
$coverage->append(
	RawCodeCoverageData::fromXdebugWithoutPathCoverage($mergedRaw),
	'merged'
);

// Merge PHPUnit CLI coverage if present
$phpunitCov = '/tmp/coverage/phpunit.cov';
if (file_exists($phpunitCov)) {
	$decoded = require($phpunitCov);
	if ($decoded instanceof CodeCoverage) {
		// Merge first to preserve raw hit data
		$coverage->merge($decoded);
		echo "[merge] Merged PHPUnit CodeCoverage successfully\n";
	} else {
		echo "[merge] The main file phpunit.cov did not return a CodeCoverage instance (" . gettype($decoded) . ")\n";
	}
} else {
	echo "[merge] The main file phpunit.cov couldn't be found.\n";
}

// Now prune unwanted files from final merged dataset
$raw = $coverage->getData(true)->lineCoverage();
$filtered = [];
foreach ($raw as $fileName => $lines) {
	if (!isExcluded($fileName)) {
		$filtered[$fileName] = $lines;
	}
	else
		echo "Excluded file {$fileName}\n";
}

// Replace with the filtered dataset once
$finalCoverage = new CodeCoverage($driver, $filter);
$finalCoverage->includeUncoveredFiles();
$finalCoverage->append(RawCodeCoverageData::fromXdebugWithoutPathCoverage($filtered),'final');

$reportDir = __DIR__ . '/../../coverage';
$phpReportDir = $reportDir . '/php';
@mkdir($phpReportDir, 0777, true);

// HTML report lives under coverage/php/ so the root coverage/index.html
// can be the combined PHP + JS overview generated by scripts/coverage-index.mjs.
$htmlReport = new HtmlReport();
$htmlReport->process($coverage, $phpReportDir);

$cloverReport = new \SebastianBergmann\CodeCoverage\Report\Clover();
$cloverReport->process($coverage, $reportDir . '/coverage.xml');

echo "✅ Merged coverage written to ./coverage\n";
