<?php

/**
 * ViteManifest
 *
 * Resolves Vite-built asset URLs for use in PHP/CakePHP templates.
 * Reads webroot/dist/.vite/manifest.json — generated by `vite build`.
 *
 * USAGE IN TEMPLATES
 * ==================
 * CSS bundle:
 *   echo ViteManifest::css('app-theme');        // <link rel="stylesheet" href="/dist/...">
 *   echo ViteManifest::cssUrl('dark-theme');    // raw URL string for use in custom tags
 *
 * JS bundle (React app):
 *   echo ViteManifest::script('app');           // <script type="module" src="/dist/...">
 *
 * Legacy JS bundle (global scope):
 *   echo ViteManifest::legacyScript('legacy');  // <script src="/dist/...">
 *
 * MANIFEST ENTRY NAMES
 * ====================
 *   'app'          → app/index.tsx              (React app)
 *   'app-theme'    → webroot/css/app-theme.js   (default.css + home-themes.css)
 *   'dark-theme'   → webroot/css/dark-theme.js  (dark-constants.css + dark.css)
 *   'light-theme'  → webroot/css/light-theme.js (light-constants.css)
 *   'legacy'       → virtual:legacy-app         (bundled legacy global JS)
 */
class ViteManifest
{
	/** Cached manifest contents after first load */
	private static ?array $manifest = null;

	/** Path to the Vite manifest file (relative to webroot) */
	private const MANIFEST_PATH = 'dist/.vite/manifest.json';

	/**
	 * Map from logical entry name → source file key used in manifest.
	 * These must match the `input` keys in vite.config.js.
	 */
	private const ENTRY_MAP = [
		'app'         => 'app/index.tsx',
		'app-theme'   => 'webroot/css/app-theme.js',
		'dark-theme'  => 'webroot/css/dark-theme.js',
		'light-theme' => 'webroot/css/light-theme.js',
		'legacy'      => 'virtual:legacy-app',
	];

	// ---------------------------------------------------------------------------
	// Public API
	// ---------------------------------------------------------------------------

	/**
	 * Returns <link rel="stylesheet"> tags for a CSS bundle entry.
	 *
	 * @param string $entry  Logical entry name (e.g. 'app-theme', 'dark-theme')
	 * @param array  $attrs  Additional HTML attributes for the <link> tag
	 */
	public static function css(string $entry, array $attrs = []): string
	{
		$url = self::cssUrl($entry);
		if ($url === null)
			return '';

		return self::linkTag($url, $attrs);
	}

	/**
	 * Returns the hashed CSS URL for a bundle entry, or null if not found in manifest.
	 */
	public static function cssUrl(string $entry): ?string
	{
		$manifest = self::load();
		$key = self::ENTRY_MAP[$entry] ?? $entry;

		// CSS proxy JS entries store the CSS files under the 'css' key
		if (isset($manifest[$key]['css'][0]))
			return '/dist/' . $manifest[$key]['css'][0];

		// Direct CSS asset (if entry is a .css file itself)
		if (isset($manifest[$key]['file']))
			return '/dist/' . $manifest[$key]['file'];

		return null;
	}

	/**
	 * Returns a plain <script> tag (no type="module") for a legacy global-scope JS bundle.
	 *
	 * Use this for the legacy app.js bundle whose functions must remain globally accessible.
	 * Loaded with a plain <script> tag so functions are in window scope.
	 *
	 * @param string $entry  Logical entry name (e.g. 'legacy')
	 * @param array  $attrs  Additional HTML attributes for the <script> tag
	 */
	public static function legacyScript(string $entry, array $attrs = []): string
	{
		$manifest = self::load();
		$key = self::ENTRY_MAP[$entry] ?? $entry;

		if (!isset($manifest[$key]['file']))
			return '';

		return self::plainScriptTag('/dist/' . $manifest[$key]['file'], $attrs);
	}

	/**
	 * Returns a <script type="module"> tag for a JS entry.
	 *
	 * @param string $entry  Logical entry name (e.g. 'app')
	 * @param array  $attrs  Additional HTML attributes for the <script> tag
	 */
	public static function script(string $entry, array $attrs = []): string
	{
		$manifest = self::load();
		$key = self::ENTRY_MAP[$entry] ?? $entry;

		if (!isset($manifest[$key]['file']))
			return '';

		return self::scriptTag('/dist/' . $manifest[$key]['file'], $attrs);
	}

	// ---------------------------------------------------------------------------
	// Internals
	// ---------------------------------------------------------------------------

	/**
	 * Load and cache the Vite manifest. Throws if manifest is not found.
	 */
	private static function load(): array
	{
		if (self::$manifest !== null)
			return self::$manifest;

		$path = WWW_ROOT . str_replace('/', DS, self::MANIFEST_PATH);

		if (!file_exists($path))
			throw new RuntimeException('Vite manifest not found at ' . $path . '. Run `pnpm build`.');

		$json = file_get_contents($path);
		if ($json === false)
			throw new RuntimeException('Failed to read Vite manifest at ' . $path);

		self::$manifest = json_decode($json, true) ?? [];
		return self::$manifest;
	}

	private static function linkTag(string $url, array $attrs = []): string
	{
		$extra = self::buildAttrs($attrs);
		return '<link rel="stylesheet" href="' . htmlspecialchars($url, ENT_QUOTES, 'UTF-8') . '"' . $extra . ' />';
	}

	private static function scriptTag(string $url, array $attrs = []): string
	{
		$extra = self::buildAttrs($attrs);
		return '<script type="module" src="' . htmlspecialchars($url, ENT_QUOTES, 'UTF-8') . '"' . $extra . '></script>';
	}

	private static function plainScriptTag(string $url, array $attrs = []): string
	{
		$extra = self::buildAttrs($attrs);
		return '<script src="' . htmlspecialchars($url, ENT_QUOTES, 'UTF-8') . '"' . $extra . '></script>';
	}

	private static function buildAttrs(array $attrs): string
	{
		$parts = [];
		foreach ($attrs as $name => $value)
		{
			if ($value === true)
				$parts[] = htmlspecialchars($name, ENT_QUOTES, 'UTF-8');
			elseif ($value !== false && $value !== null)
				$parts[] = htmlspecialchars($name, ENT_QUOTES, 'UTF-8') . '="' . htmlspecialchars($value, ENT_QUOTES, 'UTF-8') . '"';
		}
		return $parts ? ' ' . implode(' ', $parts) : '';
	}
}
